### ISSUE TITLE
 Solution in the format number/letter raises IndexOutOfRangeException

### ISSUE THREAD

**Issue by mcmalte26** [MysticMan-Game/Console#1]
If you enter the solution in the format number/letter you get a IndexOutOfRangeException

**Comment by JJauss** [comment]
I also recognized that. It's caused how the AnsweredSolution is parsed by the ShowSolution method in the MainScreen class. I think a good fix for that will be, that we validate the input before returning it back to the MainScreen. This can be done in the GameSectionBase class, in the GetSolutionMethod.

```c#
    public string GetSolution() {
      do {
        SolutionInputField.Read();
        string solution = SolutionInputField.Input;
        if (ValidateSolutionInput(solution)) {
          SolutionInputField.Clear();
          return solution;
        }
      }while(true);
    }
```
